// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 新規Vaultを作成し、RecoveryKeyを返す
Future<String> apiCreateNewVault({required String masterPassword}) =>
    RustLib.instance.api
        .crateApiApiCreateNewVault(masterPassword: masterPassword);

/// 既存Vaultをメモリに読み込む
Future<void> apiLoadVault(
        {required List<int> vaultBytes, required String etag}) =>
    RustLib.instance.api
        .crateApiApiLoadVault(vaultBytes: vaultBytes, etag: etag);

/// マスターパスワードでアンロック
Future<void> apiUnlock({required String masterPassword}) =>
    RustLib.instance.api.crateApiApiUnlock(masterPassword: masterPassword);

/// リカバリーキーでアンロック（新しいマスターパスワード設定フロー）
Future<void> apiUnlockWithRecoveryKey({required String recoveryKey}) =>
    RustLib.instance.api
        .crateApiApiUnlockWithRecoveryKey(recoveryKey: recoveryKey);

/// ロック（vault_bytesを返す）
Future<Uint8List> apiLock() => RustLib.instance.api.crateApiApiLock();

/// エントリ一覧（フィルター付き）
Future<List<DartEntryRow>> apiListEntries(
        {String? searchQuery,
        String? entryType,
        String? labelId,
        required bool includeTrash}) =>
    RustLib.instance.api.crateApiApiListEntries(
        searchQuery: searchQuery,
        entryType: entryType,
        labelId: labelId,
        includeTrash: includeTrash);

/// エントリ詳細（復号済み）
Future<DartEntry> apiGetEntry({required String id}) =>
    RustLib.instance.api.crateApiApiGetEntry(id: id);

/// エントリ作成
Future<String> apiCreateEntry(
        {required String entryType,
        required String name,
        String? notes,
        required String typedValueJson,
        required List<String> labelIds}) =>
    RustLib.instance.api.crateApiApiCreateEntry(
        entryType: entryType,
        name: name,
        notes: notes,
        typedValueJson: typedValueJson,
        labelIds: labelIds);

/// エントリ更新
Future<void> apiUpdateEntry(
        {required String id,
        String? name,
        String? notes,
        String? typedValueJson,
        List<String>? labelIds}) =>
    RustLib.instance.api.crateApiApiUpdateEntry(
        id: id,
        name: name,
        notes: notes,
        typedValueJson: typedValueJson,
        labelIds: labelIds);

/// エントリをゴミ箱へ移動
Future<void> apiDeleteEntry({required String id}) =>
    RustLib.instance.api.crateApiApiDeleteEntry(id: id);

/// ゴミ箱から復元
Future<void> apiRestoreEntry({required String id}) =>
    RustLib.instance.api.crateApiApiRestoreEntry(id: id);

/// 完全削除
Future<void> apiPurgeEntry({required String id}) =>
    RustLib.instance.api.crateApiApiPurgeEntry(id: id);

/// お気に入り設定
Future<void> apiSetFavorite({required String id, required bool isFavorite}) =>
    RustLib.instance.api.crateApiApiSetFavorite(id: id, isFavorite: isFavorite);

/// ラベル一覧
Future<List<DartLabel>> apiListLabels() =>
    RustLib.instance.api.crateApiApiListLabels();

/// ラベル作成
Future<String> apiCreateLabel({required String name}) =>
    RustLib.instance.api.crateApiApiCreateLabel(name: name);

/// ラベル削除
Future<void> apiDeleteLabel({required String id}) =>
    RustLib.instance.api.crateApiApiDeleteLabel(id: id);

/// エントリにラベルを紐付け
Future<void> apiSetEntryLabels(
        {required String entryId, required List<String> labelIds}) =>
    RustLib.instance.api
        .crateApiApiSetEntryLabels(entryId: entryId, labelIds: labelIds);

/// マスターパスワード変更
Future<void> apiChangeMasterPassword(
        {required String oldPassword, required String newPassword}) =>
    RustLib.instance.api.crateApiApiChangeMasterPassword(
        oldPassword: oldPassword, newPassword: newPassword);

/// Argon2パラメータアップグレード
Future<void> apiUpgradeArgon2Params(
        {required String password,
        required int iterations,
        required int memory,
        required int parallelism}) =>
    RustLib.instance.api.crateApiApiUpgradeArgon2Params(
        password: password,
        iterations: iterations,
        memory: memory,
        parallelism: parallelism);

/// DEK ローテーション
Future<void> apiRotateDek({required String password}) =>
    RustLib.instance.api.crateApiApiRotateDek(password: password);

/// リカバリーキー再発行
Future<String> apiRegenerateRecoveryKey({required String password}) =>
    RustLib.instance.api.crateApiApiRegenerateRecoveryKey(password: password);

/// パスワード生成
Future<String> apiGeneratePassword(
        {required int length,
        required bool includeUppercase,
        required bool includeLowercase,
        required bool includeNumbers,
        required bool includeSymbols}) =>
    RustLib.instance.api.crateApiApiGeneratePassword(
        length: length,
        includeUppercase: includeUppercase,
        includeLowercase: includeLowercase,
        includeNumbers: includeNumbers,
        includeSymbols: includeSymbols);

/// TOTP生成
Future<String> apiGenerateTotp(
        {required String secret, required int digits, required int period}) =>
    RustLib.instance.api.crateApiApiGenerateTotp(
        secret: secret, digits: digits, period: period);

/// TOTP生成（デフォルト）
Future<String> apiGenerateTotpDefault({required String secret}) =>
    RustLib.instance.api.crateApiApiGenerateTotpDefault(secret: secret);

/// 現在のvault_bytesを取得
Future<Uint8List> apiGetVaultBytes() =>
    RustLib.instance.api.crateApiApiGetVaultBytes();

/// S3から同期（コンフリクト検出）
Future<DartSyncResult> apiSync({required String storageConfig}) =>
    RustLib.instance.api.crateApiApiSync(storageConfig: storageConfig);

/// S3へプッシュ
Future<void> apiPush({required String storageConfig}) =>
    RustLib.instance.api.crateApiApiPush(storageConfig: storageConfig);

/// コンフリクト解決
Future<void> apiResolveConflict(
        {required String id, required String resolution}) =>
    RustLib.instance.api
        .crateApiApiResolveConflict(id: id, resolution: resolution);

/// Dart側で受け渡すコンフリクト情報
class DartConflict {
  final String id;
  final String entryName;
  final String conflictType;
  final DartEntry? localEntry;
  final DartEntry? remoteEntry;

  const DartConflict({
    required this.id,
    required this.entryName,
    required this.conflictType,
    this.localEntry,
    this.remoteEntry,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryName.hashCode ^
      conflictType.hashCode ^
      localEntry.hashCode ^
      remoteEntry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartConflict &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryName == other.entryName &&
          conflictType == other.conflictType &&
          localEntry == other.localEntry &&
          remoteEntry == other.remoteEntry;
}

/// Dart側で受け渡す詳細エントリデータ
class DartEntry {
  final String id;
  final String entryType;
  final String name;
  final bool isFavorite;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final String? notes;
  final String typedValue;
  final List<String> labels;

  const DartEntry({
    required this.id,
    required this.entryType,
    required this.name,
    required this.isFavorite,
    required this.updatedAt,
    this.deletedAt,
    this.notes,
    required this.typedValue,
    required this.labels,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryType.hashCode ^
      name.hashCode ^
      isFavorite.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      notes.hashCode ^
      typedValue.hashCode ^
      labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryType == other.entryType &&
          name == other.name &&
          isFavorite == other.isFavorite &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          notes == other.notes &&
          typedValue == other.typedValue &&
          labels == other.labels;
}

/// Dart側で受け渡すエントリ行データ
class DartEntryRow {
  final String id;
  final String entryType;
  final String name;
  final bool isFavorite;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;

  const DartEntryRow({
    required this.id,
    required this.entryType,
    required this.name,
    required this.isFavorite,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryType.hashCode ^
      name.hashCode ^
      isFavorite.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartEntryRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryType == other.entryType &&
          name == other.name &&
          isFavorite == other.isFavorite &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

/// Dart側で受け渡すラベル
class DartLabel {
  final String id;
  final String name;

  const DartLabel({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// 同期結果
class DartSyncResult {
  final bool hasConflicts;
  final List<DartConflict> conflicts;

  const DartSyncResult({
    required this.hasConflicts,
    required this.conflicts,
  });

  @override
  int get hashCode => hasConflicts.hashCode ^ conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartSyncResult &&
          runtimeType == other.runtimeType &&
          hasConflicts == other.hasConflicts &&
          conflicts == other.conflicts;
}
