// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1437068061;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'vault_core',
    ioDirectory: '../vault-core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiApiChangeMasterPassword(
      {required String oldPassword, required String newPassword});

  Future<String> crateApiApiCreateEntry(
      {required String entryType,
      required String name,
      String? notes,
      required String typedValueJson,
      required List<String> labelIds});

  Future<String> crateApiApiCreateLabel({required String name});

  Future<String> crateApiApiCreateNewVault({required String masterPassword});

  Future<void> crateApiApiDeleteEntry({required String id});

  Future<void> crateApiApiDeleteLabel({required String id});

  Future<String> crateApiApiGeneratePassword(
      {required int length,
      required bool includeUppercase,
      required bool includeLowercase,
      required bool includeNumbers,
      required bool includeSymbols});

  Future<String> crateApiApiGenerateTotp(
      {required String secret, required int digits, required int period});

  Future<String> crateApiApiGenerateTotpDefault({required String secret});

  Future<DartEntry> crateApiApiGetEntry({required String id});

  Future<Uint8List> crateApiApiGetVaultBytes();

  Future<List<DartEntryRow>> crateApiApiListEntries(
      {String? searchQuery,
      String? entryType,
      String? labelId,
      required bool includeTrash});

  Future<List<DartLabel>> crateApiApiListLabels();

  Future<void> crateApiApiLoadVault(
      {required List<int> vaultBytes, required String etag});

  Future<Uint8List> crateApiApiLock();

  Future<void> crateApiApiPurgeEntry({required String id});

  Future<void> crateApiApiPush({required String storageConfig});

  Future<String> crateApiApiRegenerateRecoveryKey({required String password});

  Future<void> crateApiApiResolveConflict(
      {required String id, required String resolution});

  Future<void> crateApiApiRestoreEntry({required String id});

  Future<void> crateApiApiRotateDek({required String password});

  Future<void> crateApiApiSetEntryLabels(
      {required String entryId, required List<String> labelIds});

  Future<void> crateApiApiSetFavorite(
      {required String id, required bool isFavorite});

  Future<DartSyncResult> crateApiApiSync({required String storageConfig});

  Future<void> crateApiApiUnlock({required String masterPassword});

  Future<void> crateApiApiUnlockWithRecoveryKey({required String recoveryKey});

  Future<void> crateApiApiUpdateEntry(
      {required String id,
      String? name,
      String? notes,
      String? typedValueJson,
      List<String>? labelIds});

  Future<void> crateApiApiUpgradeArgon2Params(
      {required String password,
      required int iterations,
      required int memory,
      required int parallelism});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiApiChangeMasterPassword(
      {required String oldPassword, required String newPassword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(oldPassword, serializer);
        sse_encode_String(newPassword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiChangeMasterPasswordConstMeta,
      argValues: [oldPassword, newPassword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiChangeMasterPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "api_change_master_password",
        argNames: ["oldPassword", "newPassword"],
      );

  @override
  Future<String> crateApiApiCreateEntry(
      {required String entryType,
      required String name,
      String? notes,
      required String typedValueJson,
      required List<String> labelIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(entryType, serializer);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(notes, serializer);
        sse_encode_String(typedValueJson, serializer);
        sse_encode_list_String(labelIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiCreateEntryConstMeta,
      argValues: [entryType, name, notes, typedValueJson, labelIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiCreateEntryConstMeta => const TaskConstMeta(
        debugName: "api_create_entry",
        argNames: ["entryType", "name", "notes", "typedValueJson", "labelIds"],
      );

  @override
  Future<String> crateApiApiCreateLabel({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiCreateLabelConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiCreateLabelConstMeta => const TaskConstMeta(
        debugName: "api_create_label",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiApiCreateNewVault({required String masterPassword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(masterPassword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiCreateNewVaultConstMeta,
      argValues: [masterPassword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiCreateNewVaultConstMeta => const TaskConstMeta(
        debugName: "api_create_new_vault",
        argNames: ["masterPassword"],
      );

  @override
  Future<void> crateApiApiDeleteEntry({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiDeleteEntryConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDeleteEntryConstMeta => const TaskConstMeta(
        debugName: "api_delete_entry",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiApiDeleteLabel({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiDeleteLabelConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDeleteLabelConstMeta => const TaskConstMeta(
        debugName: "api_delete_label",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiApiGeneratePassword(
      {required int length,
      required bool includeUppercase,
      required bool includeLowercase,
      required bool includeNumbers,
      required bool includeSymbols}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(length, serializer);
        sse_encode_bool(includeUppercase, serializer);
        sse_encode_bool(includeLowercase, serializer);
        sse_encode_bool(includeNumbers, serializer);
        sse_encode_bool(includeSymbols, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiGeneratePasswordConstMeta,
      argValues: [
        length,
        includeUppercase,
        includeLowercase,
        includeNumbers,
        includeSymbols
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGeneratePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_password",
        argNames: [
          "length",
          "includeUppercase",
          "includeLowercase",
          "includeNumbers",
          "includeSymbols"
        ],
      );

  @override
  Future<String> crateApiApiGenerateTotp(
      {required String secret, required int digits, required int period}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        sse_encode_u_32(digits, serializer);
        sse_encode_u_32(period, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiGenerateTotpConstMeta,
      argValues: [secret, digits, period],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGenerateTotpConstMeta => const TaskConstMeta(
        debugName: "api_generate_totp",
        argNames: ["secret", "digits", "period"],
      );

  @override
  Future<String> crateApiApiGenerateTotpDefault({required String secret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiGenerateTotpDefaultConstMeta,
      argValues: [secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGenerateTotpDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_totp_default",
        argNames: ["secret"],
      );

  @override
  Future<DartEntry> crateApiApiGetEntry({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dart_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiGetEntryConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGetEntryConstMeta => const TaskConstMeta(
        debugName: "api_get_entry",
        argNames: ["id"],
      );

  @override
  Future<Uint8List> crateApiApiGetVaultBytes() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiGetVaultBytesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGetVaultBytesConstMeta => const TaskConstMeta(
        debugName: "api_get_vault_bytes",
        argNames: [],
      );

  @override
  Future<List<DartEntryRow>> crateApiApiListEntries(
      {String? searchQuery,
      String? entryType,
      String? labelId,
      required bool includeTrash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(searchQuery, serializer);
        sse_encode_opt_String(entryType, serializer);
        sse_encode_opt_String(labelId, serializer);
        sse_encode_bool(includeTrash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dart_entry_row,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiListEntriesConstMeta,
      argValues: [searchQuery, entryType, labelId, includeTrash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiListEntriesConstMeta => const TaskConstMeta(
        debugName: "api_list_entries",
        argNames: ["searchQuery", "entryType", "labelId", "includeTrash"],
      );

  @override
  Future<List<DartLabel>> crateApiApiListLabels() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dart_label,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiListLabelsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiListLabelsConstMeta => const TaskConstMeta(
        debugName: "api_list_labels",
        argNames: [],
      );

  @override
  Future<void> crateApiApiLoadVault(
      {required List<int> vaultBytes, required String etag}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(vaultBytes, serializer);
        sse_encode_String(etag, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiLoadVaultConstMeta,
      argValues: [vaultBytes, etag],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiLoadVaultConstMeta => const TaskConstMeta(
        debugName: "api_load_vault",
        argNames: ["vaultBytes", "etag"],
      );

  @override
  Future<Uint8List> crateApiApiLock() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiLockConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiLockConstMeta => const TaskConstMeta(
        debugName: "api_lock",
        argNames: [],
      );

  @override
  Future<void> crateApiApiPurgeEntry({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiPurgeEntryConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiPurgeEntryConstMeta => const TaskConstMeta(
        debugName: "api_purge_entry",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiApiPush({required String storageConfig}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(storageConfig, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiPushConstMeta,
      argValues: [storageConfig],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiPushConstMeta => const TaskConstMeta(
        debugName: "api_push",
        argNames: ["storageConfig"],
      );

  @override
  Future<String> crateApiApiRegenerateRecoveryKey({required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiRegenerateRecoveryKeyConstMeta,
      argValues: [password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiRegenerateRecoveryKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_regenerate_recovery_key",
        argNames: ["password"],
      );

  @override
  Future<void> crateApiApiResolveConflict(
      {required String id, required String resolution}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(resolution, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiResolveConflictConstMeta,
      argValues: [id, resolution],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiResolveConflictConstMeta => const TaskConstMeta(
        debugName: "api_resolve_conflict",
        argNames: ["id", "resolution"],
      );

  @override
  Future<void> crateApiApiRestoreEntry({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiRestoreEntryConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiRestoreEntryConstMeta => const TaskConstMeta(
        debugName: "api_restore_entry",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiApiRotateDek({required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiRotateDekConstMeta,
      argValues: [password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiRotateDekConstMeta => const TaskConstMeta(
        debugName: "api_rotate_dek",
        argNames: ["password"],
      );

  @override
  Future<void> crateApiApiSetEntryLabels(
      {required String entryId, required List<String> labelIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(entryId, serializer);
        sse_encode_list_String(labelIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiSetEntryLabelsConstMeta,
      argValues: [entryId, labelIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiSetEntryLabelsConstMeta => const TaskConstMeta(
        debugName: "api_set_entry_labels",
        argNames: ["entryId", "labelIds"],
      );

  @override
  Future<void> crateApiApiSetFavorite(
      {required String id, required bool isFavorite}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_bool(isFavorite, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiSetFavoriteConstMeta,
      argValues: [id, isFavorite],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiSetFavoriteConstMeta => const TaskConstMeta(
        debugName: "api_set_favorite",
        argNames: ["id", "isFavorite"],
      );

  @override
  Future<DartSyncResult> crateApiApiSync({required String storageConfig}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(storageConfig, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dart_sync_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiSyncConstMeta,
      argValues: [storageConfig],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiSyncConstMeta => const TaskConstMeta(
        debugName: "api_sync",
        argNames: ["storageConfig"],
      );

  @override
  Future<void> crateApiApiUnlock({required String masterPassword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(masterPassword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiUnlockConstMeta,
      argValues: [masterPassword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiUnlockConstMeta => const TaskConstMeta(
        debugName: "api_unlock",
        argNames: ["masterPassword"],
      );

  @override
  Future<void> crateApiApiUnlockWithRecoveryKey({required String recoveryKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(recoveryKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiUnlockWithRecoveryKeyConstMeta,
      argValues: [recoveryKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiUnlockWithRecoveryKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_unlock_with_recovery_key",
        argNames: ["recoveryKey"],
      );

  @override
  Future<void> crateApiApiUpdateEntry(
      {required String id,
      String? name,
      String? notes,
      String? typedValueJson,
      List<String>? labelIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_opt_String(notes, serializer);
        sse_encode_opt_String(typedValueJson, serializer);
        sse_encode_opt_list_String(labelIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiUpdateEntryConstMeta,
      argValues: [id, name, notes, typedValueJson, labelIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiUpdateEntryConstMeta => const TaskConstMeta(
        debugName: "api_update_entry",
        argNames: ["id", "name", "notes", "typedValueJson", "labelIds"],
      );

  @override
  Future<void> crateApiApiUpgradeArgon2Params(
      {required String password,
      required int iterations,
      required int memory,
      required int parallelism}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        sse_encode_u_32(iterations, serializer);
        sse_encode_u_32(memory, serializer);
        sse_encode_u_32(parallelism, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApiUpgradeArgon2ParamsConstMeta,
      argValues: [password, iterations, memory, parallelism],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiUpgradeArgon2ParamsConstMeta =>
      const TaskConstMeta(
        debugName: "api_upgrade_argon2_params",
        argNames: ["password", "iterations", "memory", "parallelism"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DartEntry dco_decode_box_autoadd_dart_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dart_entry(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  DartConflict dco_decode_dart_conflict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DartConflict(
      id: dco_decode_String(arr[0]),
      entryName: dco_decode_String(arr[1]),
      conflictType: dco_decode_String(arr[2]),
      localEntry: dco_decode_opt_box_autoadd_dart_entry(arr[3]),
      remoteEntry: dco_decode_opt_box_autoadd_dart_entry(arr[4]),
    );
  }

  @protected
  DartEntry dco_decode_dart_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DartEntry(
      id: dco_decode_String(arr[0]),
      entryType: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      isFavorite: dco_decode_bool(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
      deletedAt: dco_decode_opt_box_autoadd_i_64(arr[5]),
      notes: dco_decode_opt_String(arr[6]),
      typedValue: dco_decode_String(arr[7]),
      labels: dco_decode_list_String(arr[8]),
    );
  }

  @protected
  DartEntryRow dco_decode_dart_entry_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DartEntryRow(
      id: dco_decode_String(arr[0]),
      entryType: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      isFavorite: dco_decode_bool(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
      deletedAt: dco_decode_opt_box_autoadd_i_64(arr[5]),
    );
  }

  @protected
  DartLabel dco_decode_dart_label(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DartLabel(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  DartSyncResult dco_decode_dart_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DartSyncResult(
      hasConflicts: dco_decode_bool(arr[0]),
      conflicts: dco_decode_list_dart_conflict(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DartConflict> dco_decode_list_dart_conflict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dart_conflict).toList();
  }

  @protected
  List<DartEntryRow> dco_decode_list_dart_entry_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dart_entry_row).toList();
  }

  @protected
  List<DartLabel> dco_decode_list_dart_label(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dart_label).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DartEntry? dco_decode_opt_box_autoadd_dart_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dart_entry(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DartEntry sse_decode_box_autoadd_dart_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dart_entry(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  DartConflict sse_decode_dart_conflict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_entryName = sse_decode_String(deserializer);
    var var_conflictType = sse_decode_String(deserializer);
    var var_localEntry = sse_decode_opt_box_autoadd_dart_entry(deserializer);
    var var_remoteEntry = sse_decode_opt_box_autoadd_dart_entry(deserializer);
    return DartConflict(
        id: var_id,
        entryName: var_entryName,
        conflictType: var_conflictType,
        localEntry: var_localEntry,
        remoteEntry: var_remoteEntry);
  }

  @protected
  DartEntry sse_decode_dart_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_entryType = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isFavorite = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_deletedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_typedValue = sse_decode_String(deserializer);
    var var_labels = sse_decode_list_String(deserializer);
    return DartEntry(
        id: var_id,
        entryType: var_entryType,
        name: var_name,
        isFavorite: var_isFavorite,
        updatedAt: var_updatedAt,
        deletedAt: var_deletedAt,
        notes: var_notes,
        typedValue: var_typedValue,
        labels: var_labels);
  }

  @protected
  DartEntryRow sse_decode_dart_entry_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_entryType = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isFavorite = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_deletedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return DartEntryRow(
        id: var_id,
        entryType: var_entryType,
        name: var_name,
        isFavorite: var_isFavorite,
        updatedAt: var_updatedAt,
        deletedAt: var_deletedAt);
  }

  @protected
  DartLabel sse_decode_dart_label(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return DartLabel(id: var_id, name: var_name);
  }

  @protected
  DartSyncResult sse_decode_dart_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasConflicts = sse_decode_bool(deserializer);
    var var_conflicts = sse_decode_list_dart_conflict(deserializer);
    return DartSyncResult(
        hasConflicts: var_hasConflicts, conflicts: var_conflicts);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DartConflict> sse_decode_list_dart_conflict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DartConflict>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dart_conflict(deserializer));
    }
    return ans_;
  }

  @protected
  List<DartEntryRow> sse_decode_list_dart_entry_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DartEntryRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dart_entry_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<DartLabel> sse_decode_list_dart_label(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DartLabel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dart_label(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DartEntry? sse_decode_opt_box_autoadd_dart_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dart_entry(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dart_entry(
      DartEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dart_entry(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_dart_conflict(DartConflict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.entryName, serializer);
    sse_encode_String(self.conflictType, serializer);
    sse_encode_opt_box_autoadd_dart_entry(self.localEntry, serializer);
    sse_encode_opt_box_autoadd_dart_entry(self.remoteEntry, serializer);
  }

  @protected
  void sse_encode_dart_entry(DartEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.entryType, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isFavorite, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.deletedAt, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_String(self.typedValue, serializer);
    sse_encode_list_String(self.labels, serializer);
  }

  @protected
  void sse_encode_dart_entry_row(DartEntryRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.entryType, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isFavorite, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.deletedAt, serializer);
  }

  @protected
  void sse_encode_dart_label(DartLabel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_dart_sync_result(
      DartSyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasConflicts, serializer);
    sse_encode_list_dart_conflict(self.conflicts, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dart_conflict(
      List<DartConflict> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dart_conflict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dart_entry_row(
      List<DartEntryRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dart_entry_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dart_label(
      List<DartLabel> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dart_label(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dart_entry(
      DartEntry? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dart_entry(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
